export const relationships = [
  "Parent",
  "Spouse",
  "Sibling",
  "Child",
  "Grandparent",
  "Aunt/Uncle",
  "Cousin",
  "Friend",
  "Roommate",
  "Co-worker",
  "Neighbor",
  "Partner",
  "Guardian",
  "Caregiver",
  "Coach/Teacher",
  "Doctor",
  "Religious Leader",
  "Landlord",
  "Legal Representative",
  "Employer",
  "Social Worker",
  "Family Friend",
  "Personal Trainer",
  "Mentor",
  "Ex-Spouse",
  "Godparent",
  "Therapist/Counselor",
  "Pet Sitter",
  "Next of Kin",
  "Legal Guardian"
];