const languages: string[] = [
  "English",
  "Spanish",
  "French",
  "German",
  "Japanese",
  "Chinese",
  "Italian",
  "Russian",
  "Arabic",
  "Portuguese",
  "Dutch",
  "Korean",
  "Swedish",
  "Danish",
  "Norwegian",
  "Finnish",
  "Greek",
  "Turkish",
  "Hindi",
  "Bengali",
  "Urdu",
  "Swahili",
  "Vietnamese",
  "Thai",
  "Hebrew",
  "Polish",
  "Czech",
  "Hungarian",
  "Romanian",
  "Ukrainian",
  "Farsi (Persian)",
  "Malay",
  "Indonesian",
  "Filipino",
  "Maltese",
  "Sanskrit",
  "Icelandic",
  "Mongolian",
  "Kurdish",
  "Fijian",
  "Samoan",
  "Tahitian",
  "Maori",
  "Hawaiian",
  "Navajo",
  "Inuktitut",
  "Esperanto",
  "Klingon" // Just for fun!
];

export const getRandomLanguage = () => {
  return languages[Math.floor(Math.random() * languages.length)];
}

// You can add more languages as needed.
